DROP TABLE TEST.Transaction;
CREATE COLUMN TABLE TEST.Transaction (
	ID INTEGER,
	TransactionValue DECIMAL,
	TransactionCode VARCHAR(255),
	PRIMARY KEY (ID));

		
INSERT INTO TEST.Transaction VALUES (1, 0.45, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (2, 23.3342, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (3, 1.23, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (4, 0, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (5, 15.01, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (6, 7, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (7, 2.223, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (8, 83.234, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (9, 9.0023, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (10, 1.001, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (11, 1.004, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (12, 0, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (13, 0, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (14, 63.03, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (15, 14.933, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (16, 0.3409, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (17, -23.34, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (18, 0, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (19, -4.009, SYSUUID);  
INSERT INTO TEST.Transaction VALUES (20, 1.0231, SYSUUID);  
		